Incorporated ProgressMeter and fixed raw data plotting
Orchard-Ultrasound-Innovation/IntensityScans.jl pull request #19
Opened 2021-09-17 19:10 UTC by stevenaleung

2021-09-22 08:06 UTC, mofii requested changes
See the comments within

2021-09-22 08:06 UTC, mofii commented on src/scan_xyz.jl
> +        ProgressMeter.update!(pm)
Same comment as the one previously made, are you sure this is necessary?

2021-09-22 08:06 UTC, mofii commented on src/single_axis_scan.jl
>  using Dates
Also move these package inclusions

2021-09-22 08:06 UTC, mofii commented on src/single_axis_scan.jl
> +        ProgressMeter.update!(pm)
It's here as well

2021-09-22 08:06 UTC, mofii commented on src/util.jl
> +using Unitful
Another one

2021-09-22 17:40 UTC, stevenaleung commented on src/double_axis_scan.jl
> +using ProgressMeter
Can do

2021-09-22 17:45 UTC, stevenaleung commented on src/double_axis_scan.jl
> +        ProgressMeter.update!(pm)
ProgressMeter by default shows the progress bar after the 2nd iteration. The reasoning is that using 2 iterations of timing data can provide a better estimate of remaining time. With the raster scans, each plane can take 1+ min depending on the number of acquisition points, so it would take 2+ min before a progress bar is shown. I'm using update!() here to force the bar to be shown right away so that the user knows the code is running properly

2021-09-23 05:30 UTC, mofii commented on src/double_axis_scan.jl
> +        ProgressMeter.update!(pm)
Ok, I'm convinced

2021-09-23 05:33 UTC, mofii approved these changes

2021-09-23 16:23 UTC, merged